# Generated by Django 5.2.5 on 2025-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('telegram', 'Telegram'), ('twitter', 'X (Twitter)'), ('whatsapp', 'WhatsApp'), ('amazon_music', 'Amazon Music'), ('apple_music', 'Apple Music'), ('deezer', 'Deezer'), ('soundcloud', 'SoundCloud'), ('spotify', 'Spotify'), ('tidal', 'Tidal'), ('twitch', 'Twitch'), ('youtube', 'YouTube'), ('youtube_music', 'YouTube Music'), ('snapchat', 'SnapChat'), ('custom', 'Custom Website')], max_length=30),
        ),
    ]
