# Generated by Django 5.2.5 on 2025-08-07 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('channel_name', models.CharField(blank=True, max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to='cover_track/')),
                ('creator_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(blank=True, choices=[('music', 'Música'), ('podcast', 'Podcast'), ('news', 'Noticias'), ('gaming', 'Gaming'), ('sports', 'Deportes'), ('comedy', 'Comedia'), ('vlog', 'Vlogs / Vida Diaria'), ('education', 'Educación'), ('technology', 'Tecnología'), ('howto', 'Tutoriales / How-To'), ('entertainment', 'Entretenimiento'), ('fashion', 'Moda / Belleza'), ('health', 'Salud y Bienestar'), ('food', 'Comida / Cocina'), ('travel', 'Viajes'), ('documentary', 'Documentales'), ('interview', 'Entrevistas'), ('motivational', 'Motivacional / Inspiración'), ('review', 'Reseñas / Opiniones'), ('shortfilm', 'Cortometrajes / Cine'), ('animation', 'Animación'), ('religion', 'Religión / Espiritualidad'), ('business', 'Negocios / Emprendimiento'), ('finance', 'Finanzas / Economía'), ('science', 'Ciencia'), ('politics', 'Política / Sociedad'), ('kids', 'Contenido Infantil'), ('art', 'Arte / Cultura'), ('automotive', 'Automóviles / Mecánica'), ('realestate', 'Bienes Raíces'), ('other', 'Otro')], max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Palabras clave separadas por coma', max_length=250)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('subgenre', models.CharField(blank=True, max_length=100)),
                ('album_or_series', models.CharField(blank=True, help_text='Nombre del álbum, serie o playlist', max_length=150)),
                ('is_collaboration', models.BooleanField(default=False)),
                ('composer', models.CharField(blank=True, max_length=150)),
                ('producer', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
